name: Build

on:
  push:
    #branches:
    #  - develop
    tags:
      - v*

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - kind: linux
            os: ubuntu-latest
            platform: linux
          - kind: windows
            os: windows-latest
            platform: win
          - kind: mac
            os: macos-11
            platform: osx
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          # The talk on the street says this might be a good version for building.
          node-version: 14.20.1
          cache: yarn

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - if: matrix.platform == 'linux'
        name: Install bsdtar # Required by electron-builder when targeting pacman.
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libarchive-tools

      - name: Build project
        id: build
        uses: StarUbiquitous/command-output@v1.0.1 # Store stdout/stderr to outputs.
        # You might want to turn this on if there's problems with electron-builder.
        # env:
        #   DEBUG: electron-builder
        with:
          run: yarn build-${{ matrix.platform }} --publish=never

      - if: steps.build.outputs.stderr != ''
        name: Log stderr
        continue-on-error: true
        run: echo '${{ steps.build.outputs.stderr }}'

      - name: Get commits since version
        id: commits
        run: echo ::set-output name=value::$(git log "$(git describe --tags --abbrev=0)..HEAD" --no-merges --oneline)
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          body: |
            ${{ steps.commits.outputs.value }}
          files: |
            dist/electron/Packaged/*.yml
            dist/electron/Packaged/*.yaml
            dist/electron/Packaged/*.deb
            dist/electron/Packaged/*.dmg
            dist/electron/Packaged/*.exe
            dist/electron/Packaged/*.blockmap
            dist/electron/Packaged/*.rpm
            dist/electron/Packaged/*.zip
            dist/electron/Packaged/*.AppImage
            dist/electron/Packaged/*.pacman
            dist/electron/Packaged/*.tar.gz

      # Creating Electron executables can in some cases fail with exit code 0.
      # Check the output of build step for obvious signs of failure.
      - if: contains(steps.build.outputs.stderr, '[FAIL]')
        name: Check STDERR for trouble
        uses: actions/github-script@v6
        with:
          script: core.setFailed('It seems the build process failed silently. See previous step for more info.')
